### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brandonyu5**

### CODE REVIEW

**Comment by brandonyu5** [comment]
sir please let me in

**Comment by brandonyu5** [comment]
GUYS PLS I NEED TO PULL

**Review by ericgong5 — COMMENTED** [review]
lgtm

**Review by aetdc — COMMENTED** [review]
LGTM!

**Review by austinbarrows — APPROVED** [review]
this is very poggin as they kids would say in these modern times indeed

**Comment by brandonyu5** [comment]
thanks guys. id like to thank my family and friends

**Comment by ericgong5** [comment]
ggg

**Comment by ericgong5** [comment]
get back to work wage slave

**Pull request merged**
